services:
  chess-analyzer:
    build: .
    container_name: chess-analyzer
    ports:
      - "8000:8000"
    volumes:
      # auto reload
      - ./app:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=${GROQ_API_KEY}
    command: python main.py
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: chess-analyzer-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
