version: '3.8'

services:
  chess-analyzer:
    build: .
    container_name: chess-analyzer
    ports:
      - "8000:8000"
    volumes:
      # auto reload
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: chess-analyzer-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


