services:
  chess-analyzer:
    build: ./backend
    container_name: chess-analyzer
    ports:
      - "8000:8000"
    volumes:
      # auto reload
      - ./backend/app:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=${GROQ_API_KEY}
    # command: python main.py
    # command: sleep infinity
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: chess-analyzer-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dashboard:
    build: ./backend
    container_name: chess-analyzer-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./backend/app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY=${GROQ_API_KEY}
    command: streamlit run dashboard.py --server.address=0.0.0.0
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
